#!/bin/sh
#
# This is a script that uses ImageMagick to resize (downsize only) all images at a directory path to a specified size.
#
# Accepts: 	png, jpg, jpeg, gif
# Outputs: 	png
# Usage: 	./imageResizeBatch.sh WIDTH HEIGHT directoryPath
# Ex:		./imageResizeBatch.sh 320 480 ~
# 
# Latest Test Environment
# OSX:			10.12.3
# ImageMagick:	7.0.5-4 Q16 x86_64
# 


# =====================================
# ==========[ Library Check ]==========
# =====================================

command -v convert >/dev/null 2>&1 || { 
	echo >&2 'Error: cannot find "convert" command.... Is ImageMagick installed?'; 
	exit 1; 
}

# ================================================
# ==========[ Arguments Validity Check ]==========
# ================================================

if [ "$#" -ne 3 ]; then
	echo "Error:   Incorrect number of arguments"
	echo "Usage:   imageResizeBatch.sh WIDTH HEIGHT dirPath"
	echo "Example: imageResizeBatch 360 480 ~"
	exit 1
fi

width=$1
height=$2
dirPath=$3

numRegExp='^[0-9]+$'
if ! [[ $width =~ $numRegExp ]] ; then
   echo "Error: Width is not a valid number" >&2
   exit 1
fi
if ! [[ $height =~ $numRegExp ]] ; then
   echo "Error: Height is not a valid number" >&2
   exit 1
fi
if [ ! -d "$dirPath" ]; then
   echo "Error: Directory path does not exist ($dirPath)" >&2
   exit 1
fi

echo "Resolution:" "$width""x""$height"
echo "Begin Conversion"

# ===================================================
# ==========[ Find num conversions needed ]==========
# ===================================================

numConversions=0
for f in *
do
    fileFullName=`echo $f|grep -i ".png\|.jpg\|.jpeg\|.gif"`
	fileName="${fileFullName%.*}"
	fileExt="${fileFullName##*.}"
	if [ -n "$fileFullName" ] ; then
    	let "numConversions += 1"
    fi
done

# ==================================
# ==========[ Conversion ]==========
# ==================================

curConversion=0
for f in *
do
	let "curConversion += 1"
	echo "[""$curConversion"" / "" $numConversions""]"

    fileFullName=`echo $f|grep -i ".png\|.jpg\|.jpeg\|.gif"`
	fileName="${fileFullName%.*}"
	fileExt="${fileFullName##*.}"
	if [ -n "$fileFullName" ] ; then
    	let "numConversions += 1"
    fi
done

printf "All done!\n\n"

