#!/bin/sh
#
# Uses ImageMagick to convert all images in directory to PNG format
#
# Accepts: 	png, jpg, jpeg, gif
# Outputs: 	png
# Usage: 	./imageRemoveBgWhiteBatch DIRPATH
# Ex:		./imageRemoveBgWhiteBatch ~
# 
# Latest Test Environment
# OSX:			10.12.3
# ImageMagick:	7.0.5-4 Q16 x86_64
# 

# =====================================
# ==========[ Library Check ]==========
# =====================================

command -v convert >/dev/null 2>&1 || { 
	echo >&2 'Error: cannot find "convert" command.... Is ImageMagick installed?'; 
	exit 1; 
}

# ================================================
# ==========[ Arguments Validity Check ]==========
# ================================================

if [ "$#" -ne 1 ]; then
	echo "Error: Incorrect number of arguments ($#). Needs to be 1."
	echo "Usage: imageToPngBatch DIRPATH"
	echo "Example: imageToPngBatch ~"
	exit 1
fi

dirPath=$1

if [ ! -d "$dirPath" ]; then
   echo "Error: Directory path does not exist ($dirPath)" >&2
   exit 1
fi



# ===================================================
# ==========[ Find num conversions needed ]==========
# ===================================================

numToProcess=0
for f in *
do
    fileFullName=`echo $f|grep -i ".png\|.jpg\|.jpeg\|.gif\|.tiff"`
	fileName="${fileFullName%.*}"
	fileExt="${fileFullName##*.}"
	if [ -n "$fileFullName" ] ; then
    	let "numToProcess += 1"
    fi
done

# ==================================
# ==========[ Conversion ]==========
# ==================================

curProcess=0

for f in *
do
	let "curProcess += 1"
	echo "[""$curProcess"" / "" $numToProcess""]"

	fileFullName=`echo $f|grep -i ".png\|.jpg\|.jpeg\|.gif\|.tiff"`
	if [ -n "$fileFullName" ] ; then
		imageToPng $fileFullName
	fi
done

printf "All done!\n\n"
