#!/bin/sh
#
# Uses ImageMagick to convert an image to PNG format
# This will also clean the image of metadata
#
# Accepts: 	png, jpg, jpeg, gif
# Outputs: 	png
# Usage: 	./imageToPng FILENAME
# Ex:		./imageToPng image.png
# 
# Latest Test Environment
# OSX:			10.12.3
# ImageMagick:	7.0.5-4 Q16 x86_64
# 

# =====================================
# ==========[ Library Check ]==========
# =====================================

command -v convert >/dev/null 2>&1 || { 
	echo >&2 'Error: cannot find "convert" command.... Is ImageMagick installed?'; 
	exit 1; 
}

# ================================================
# ==========[ Arguments Validity Check ]==========
# ================================================

if [ "$#" -ne 1 ]; then
	echo "Error: Incorrect number of arguments ($#). Needs to be 1."
	echo "Usage: imageToPng FILENAME"
	echo "Example: imageToPng test.png"
	exit 1
fi

filePath=$1

if [ ! -f "$filePath" ]; then
	echo "File ($filePath) not found!"
	exit 1
fi

fileFullName=`echo $filePath|grep -i ".png\|.jpg\|.jpeg\|.gif\|.tiff"`
if [ ! -n "$fileFullName" ] ; then
	echo "File not a valid format (png,jpg,jpeg,gif,tiff)"
	exit 1
fi

# ==========================================
# ==========[ Converting Process ]==========
# ==========================================

echo "File: \t\t"$fileFullName
printf "Converting:\t...."

fileName="${fileFullName%.*}"
fileExt="${fileFullName##*.}"

# 1/3 - The actual conversion
convert "$fileName"".""$fileExt" "$fileName"".png"

# 2/3 - Strip all comments and PNG-metadata-chunks
convert "$fileFullName" -strip "$fileFullName"

# 3/3 - If was not originally PNG - remove the old file
if [ $fileExt != "png" ] ; then
	rm $fileFullName
fi

echo " Done!"		
